### ISSUE TITLE
Legit?

### ISSUE THREAD

**Issue by Xordevv** [Midoriykawa/Bernkastel-crack-allKlass#1]
I doubt its legit as its more like a "fine tuned" from old script according to a friend, there are skills not supported on this crack version but the original scripts already supported. Whoever buying this, DONT TRUST OR BUY better off with NGSP!

**Comment by Midoriykawa** [comment]
Everything works fine for me and everyone who bought from me has a discord open and I accept all reports. Everything works for everyone)

**Comment by Tera-Scripts** [comment]
You are sad. people can see u edit my comments :)

Stop scamming people ty.

**Comment by Tera-Scripts** [comment]
You are sad. people can see u edit my comments :)

Stop scamming people ty.

It doesn't work.
