### ISSUE TITLE
You are sad. people can see u edit my comments :)  Stop scamming people ty.

### ISSUE THREAD

**Issue by Tera-Scripts** [Midoriykawa/Bernkastel-crack-allKlass#2]
Very embarrassing to advertise. Will stop working soon on new patch. Don't waste money friends.

You are sad. people can see u edit my comments :)

Stop scamming people ty.

**Comment by Midoriykawa** [comment]
u dont buy script:D stfu scamer' all work

**Comment by Tera-Scripts** [comment]
stop scamming people, and editing my message, its not legit versions as new ones have proper protection, stupid

**Comment by Midoriykawa** [comment]
stop trolling trash u dont buy my script / all work. muted

**Comment by Midoriykawa** [comment]
all legit:D

**Comment by Tera-Scripts** [comment]
You are sad. people can see u edit my comments :)

Stop scamming people ty.
